### ISSUE TITLE
[2] Find a suitable service for mapping zipcodes -> counties

### ISSUE THREAD

**Issue by mdworken** [loyno-mathcs/partner#5]
We store info on clients, areas served, etc in the form of zip-codes, but some partner's are interested in being able to see a county-level view as well. To do this, we'd like to use an API that can take a list of 1 or more zip codes, and will return the corresponding counties.

- [ ] Do some research on free-tier APIs that can do this for us. Some possibilities include USPS, Google Maps, Apple Maps, Mapbox, etc.

- [ ] Comment on this ticket with your recommendation and any appropriate justifications.

Note: This task does NOT require a PR, and may be a good fit for anyone who is still having trouble with their environment setup.

**Comment by jjlahatte** [comment]
i would like to be assigned to this issue, but I cannot assign myself

**Comment by jjlahatte** [comment]
The USPS (post office) zip code API would be the most appropriate for this project, the API matches the municipality with a user entered zip code and accounts for zip codes that may span county boundaries by displaying both counties. The API is also free to use unlike the Google maps API which if free would be more suitable (in my opinion); however, the USPS service is completely free and looks like it would be relatively easy to implement in the app; and it also has a developer guide that walks you through some of the implementation process which makes it good for this team because we all are novices in the field.

**Comment by jjlahatte** [comment]
From the website:
Developers integrating Web Tools into a custom application:
The following are the production URLs you will use to access the Web Tools Servers:
 - http://production.shippingapis.com/ShippingAPI.dll
 - https://secure.shippingapis.com/ShippingAPI.dll
Step-by-Step Instructions for All USPS Web Tools (important information when getting started):
 - https://www.usps.com/business/web-tools-apis/general-api-developer-guide.pdf

API User’s Guides (API specific technical/integration information):
 - https://www.usps.com/business/web-tools-apis/technical-documentation.htm

USPS Web Tools website: (contains all these resources and more):
 - https://www.usps.com/business/web-tools-apis/welcome.htm

**Comment by nihonjinrxs** [comment]
@jjlahatte don't forget about closing out this one from the prior sprint. You may want to request a review from @mdworken in a comment here.

**Comment by jjlahatte** [comment]
@mdworken  this issue is ready for review

**Comment by nihonjinrxs** [comment]
@mdworken are we OK on this one, or do you need more information? Would be good to close this if it's done.

**Comment by mdworken** [comment]
This looks excellent, consider it completed!
